import {Injectable} from '@angular/core'

import {Content} from './content.model'

@Injectable()
export class ContentService{
    private _allContent:Array<Content> = [
        {
            elemCode: 'discBrake',
            elemName: 'Disc Brakes',
            youTubeUrl: 'https://www.youtube.com/watch?v=MAuVDB-G-HQ',
            sampleImageUrl: 'https://r.hswstatic.com/w_285/gif/disc-brake3.jpg',
            explanation: 'The disc brake is a lot like the brakes on a bicycle. Bicycle brakes have a caliper, which squeezes the brake pads against the wheel. In a disc brake, the brake pads squeeze the rotor instead of the wheel, and the force is transmitted hydraulically instead of through a cable. Friction between the pads and the disc slows the disc down.\
            <br/>A moving car has a certain amount of kinetic energy, and the brakes have to remove this energy from the car in order to stop it. How do the brakes do this? Each time you stop your car, your brakes convert the kinetic energy to heat generated by the friction between the pads and the disc. Most car disc brakes are vented.',
            references: [
                'https://auto.howstuffworks.com/auto-parts/brakes/brake-types/disc-brake1.htm'
            ]
        }
    ];

    public getContent(elemCode:string):Promise<Content>{
        return new Promise( (resolve, reject) => {
            let tempContent = this._allContent.find(cont => cont.elemCode==elemCode)

            if(tempContent) resolve(tempContent)
            else reject("Content for such element does not exist")
        });
    }
}