import {Injectable} from '@angular/core'

import {Content} from './content.model'
import { Subject } from 'rxjs/Rx';

@Injectable()
export class ContentService{

    private _activeContent$ = new Subject<Content>();

    public observeActiveContent(){
        return this._activeContent$;
    }

    public updateActiveContent(content:Content){
        this._activeContent$.next(content);
    }

    private _allContent:Array<Content> = [
        {
            elemCode: 'discBrake',
            elemName: 'Disc Brakes',
            parentGrpName: 'SuspBreakSys',
            youTubeUrl: 'https://www.youtube.com/embed/MAuVDB-G-HQ',
            sampleImageUrl: 'http://www.acuravigorclub.com/Timely-Topics/TTGraphics/1204/CaliperAnimation.gif',
            // sampleImageUrl: 'https://r.hswstatic.com/w_285/gif/disc-brake3.jpg',
            explanation: 'The disc brake is a lot like the brakes on a bicycle. Bicycle brakes have a caliper, which squeezes the brake pads against the wheel. In a disc brake, the brake pads squeeze the rotor instead of the wheel, and the force is transmitted hydraulically instead of through a cable. Friction between the pads and the disc slows the disc down.\
            <br/>A moving car has a certain amount of kinetic energy, and the brakes have to remove this energy from the car in order to stop it. How do the brakes do this? Each time you stop your car, your brakes convert the kinetic energy to heat generated by the friction between the pads and the disc. Most car disc brakes are vented.',
            references: [
                'https://auto.howstuffworks.com/auto-parts/brakes/brake-types/disc-brake1.htm'
            ],
            arrow_tail_path_d:'M346,347 C286,437 350,475 455,486',
            arrow_head_path_d:'M416,504 C500,469 482,511 440,442'

        },
        {
            elemCode: 'tyres',
            elemName: 'Tyre Components & Dimensions',
            parentGrpName: 'SuspBreakSys',
            youTubeUrl: 'https://www.youtube.com/embed/K3qkkp4aPJk',
            sampleImageUrl: 'http://www.imagequiz.co.uk/img?img_id=ag5zfmltYWdlbGVhcm5lcnIOCxIHUXVpenplcxjGPgw',
            // sampleImageUrl: 'https://r.hswstatic.com/w_285/gif/disc-brake3.jpg',
            explanation: '<h5>Tyre components</h5>\
            <h6>A. Tire Belts</h6>\
            Rubber-coated layers of steel, fiberglass, rayon, and other materials located between the tread and plies, crisscrossing at angles, hold the plies in place. Belts provide resistance to punctures and help treads stay flat and in contact with the road. \
            <h6>B. Tire Sipes</h6>\
            Sipes are special treads within the tread that improve traction on wet, dirty, sandy, or snowy road surfaces. \
            <h6>C. Tire Tread</h6>\
            The portion of the tire that comes in contact with the road. \
            <h6>D. Tire Grooves</h6>\
            The spaces between two adjacent tread ribs are also called tread grooves. These allow water to escape effectively. \
            <h6>E. Tire Shoulder</h6>\
            The outer edge of the tread that wraps into the sidewall area.\
            <h6>F. Tire Sidewall</h6>\
            The sidewall of the tire protects cord plies and features tire markings and information such as tire size and type.\
            <h6>G. Tire Inner Liner</h6>\
            This is the innermost layer of a tubeless tire that prevents air from penetrating the tire. \
            <h6>H. Tire Bead</h6>\
            A rubber-coated loop of high-strength steel cable that allows a tire to stay "seated" on a rim.\
            <h6>I. Tire Body Plies</h6>\
            This is the tire itself, made up of several layers of plies. Plies, like polyester cord, run perpendicular to the tire\'s tread and are coated with rubber to help bond with other plies and belts to seal in air. Plies give tires strength and resistance to road damage.\
            <h4 id=\'tyres_tyre_size_read\'>HOW TO READ YOUR TYRE SIZE</h4>\
            Example: 215/60R15</br>\
            <ul><li>215 is the width of the tyre in millimetres.</li>\
            <li>60 is the aspect ratio or tyre profile.</li>\
            <li>R means it is radial construction.</li>\
            <li>15 is the diameter of the wheel rim in inches.</li>',
            references: [
                'http://www.mycertifiedservice.com/parts-of-a-tire.html',
                'https://www.dunlop.eu/en_gb/motorcycle/learn/tyres-explained.html',
                'https://auto.howstuffworks.com/tire1.htm'
            ],
            arrow_tail_path_d:'M324,373 C286,437 350,475 515,496',
            arrow_head_path_d:'M446,514 C530,479 512,521 470,452'

        },
		{
            elemCode: 'drumBrake',
            elemName: 'Drum Brakes',
            parentGrpName: 'SuspBreakSys',
            youTubeUrl: 'https://www.youtube.com/embed/bnc3VnQ8kUY',
            // sampleImageUrl: 'https://media.giphy.com/media/MbMhShwKsjJPa/giphy.gif',
            sampleImageUrl: 'http://www.mechanicalbooster.com/wp-content/uploads/2017/11/drum-brake-modal.png',
            explanation: '<ol> <li>As the brake pedal is pressed, it compresses the fluid in the master cylinder and allows the piston of the wheel cylinder to expand outward.</li>\
			<li>The outward motion of the piston of wheel cylinder forces the brake shoe outward against the brake drum.\
			<li>As the brake shoe lining touches the inner surface of the drum, and due to the friction generated in between the brake shoe and drum, the motion of the wheel reduces and vehicle stops.</li>\
			<li>As the force is removed from the brake pedal, the retracting springs draws the brake shoe inward and the contact between the friction lining and drum ended. Now again the brake is ready to apply.</li>\
			<li>A self adjusting screw is present at the bottom, which is used to maintain a minimum gap between the drum and brake shoe. When the lining of the brake shoe is wear out than the gap between the drum and brake shoe increases, at that time the adjuster is adjusted again to maintain the minimum gap.</li>\
			</ul>',
            references: [
                'http://www.mechanicalbooster.com/2017/11/how-drum-brakes-work.html'
            ],
            arrow_tail_path_d:'M333,399 C282,459 316,491 382,487',
            arrow_head_path_d:'M351,511 C436,481 388,522 376,460'
        },
		{
            elemCode: 'radiator',
            elemName: 'Radiator',
            parentGrpName: 'CoolSys',
            youTubeUrl: 'https://www.youtube.com/embed/V7inC4lOpGs',
            sampleImageUrl: 'https://image.cpsimg.com/sites/carparts-mc/assets/classroom/images/cooling-system.gif',
            explanation: 'A thermostat at the front of the engine detects when the engine reaches an unacceptable temperature. This triggers the release of water and coolant—both of which are held in the radiator.<br/>\
			This liquid combination picks up the heat generated by engine friction and burned fuel. It is then sent back into the radiator itself. The surface area is ample enough to let the coolant cool. Additionally, a fan positioned near it helps cool the coolant further.<br/>\
			Air from outside the car is brought in through vents, providing further cooling power. The coolant, sufficiently cooled down, can then be sent back into the engine to pick up more heat.',
            references: [
                'https://www.meineke.com/blog/how-does-a-radiator-work/',
				'https://auto.howstuffworks.com/cooling-system6.htm',
				'https://www.howacarworks.com/basics/how-an-engine-cooling-system-works'
            ],
            arrow_tail_path_d:'M160,312 C84,377 192,462 397,498',
            arrow_head_path_d:'M356,524 C440,489 422,531 380,462'
        },
		{
            elemCode: 'engineRWD',
            elemName: '4 Stroke Engine',
            parentGrpName: 'RWD',
            youTubeUrl: 'https://www.youtube.com/embed/OGj8OneMjek',
            sampleImageUrl: 'https://i2.wp.com/mechstuff.com/wp-content/uploads/2015/10/4StrokeEngine_Ortho_3D_Small.gif?resize=225%2C300',
            explanation: '<h5>Step 1: Intake Stroke</h5>\
				Air and fuel enter the small engine through the carburetor. It’s the job of the carburetor to supply a mixture of air and fuel that will allow for proper combustion. During the intake stroke, the intake valve between the carburetor and combustion chamber opens. This allows atmospheric pressure to force the air-fuel mixture into the cylinder bore as the piston moves downward.\
				<h5>Step 2: Compression Stroke</h5>\
				Just after the piston moves to the bottom of its travel (bottom dead center), the cylinder bore contains the maximum air-fuel mixture possible. The intake valve closes and the piston returns back up the cylinder bore. This is called the compression stroke of the 4-cycle engine process. The air-fuel mixture is compressed between the piston and cylinder head.\
				<h5>Step 3: Power Stroke</h5>\
				When the piston reaches the top of its travel (top dead center), it will be at its optimum point to ignite the fuel to get maximize power to your outdoor power equipment. A very high voltage is created in the ignition coil. The spark plug enables this high voltage to be discharged into the combustion chamber. The heat created by the spark ignites the gases, creating rapidly expanding, super-heated gases that force the piston back down the cylinder bore. This is called the power stroke.\
				<h5>Step 4: Exhaust Stroke</h5>\
				When the piston reaches bottom dead center again, the exhaust valve opens. As the piston travels back up the cylinder bore, it forces the spent combustion gases through the exhaust valve and out of the exhaust systems. As the piston returns to top dead center, the exhaust valve closes and the intake valve opens and the 4-cycle engine process repeat.\
				Ever repetition of the cycle requires two full rotations of the crankshaft, while the engine only creates power during one of the four strokes. To keep the machine running, it needs the small engine flywheel. The power stroke creates momentum that pushes the flywheel’s inertia keeps it and the crankshaft turning during the exhaust, intake and compression strokes.',
            references: [
                'http://www.animatedengines.com/otto.html',
				'https://www.linkedin.com/pulse/20140717090644-133229807-principles-and-working-of-four-stroke-gasoline-engine',
				'https://www.briggsandstratton.com/na/en_us/support/videos/browse/4-cycle-theory.html'
            ],
            arrow_tail_path_d:'M244,339 C163,473 351,475 582,487',
            arrow_head_path_d:'M551,511 C636,481 588,522 576,460'
        },
        {
            elemCode: 'engineFWD',
            elemName: '4 Stroke Engine',
            parentGrpName: 'FWD',
            youTubeUrl: 'https://www.youtube.com/embed/OGj8OneMjek',
            sampleImageUrl: 'https://i2.wp.com/mechstuff.com/wp-content/uploads/2015/10/4StrokeEngine_Ortho_3D_Small.gif?resize=225%2C300',
            explanation: '<h5>Step 1: Intake Stroke</h5>\
				Air and fuel enter the small engine through the carburetor. It’s the job of the carburetor to supply a mixture of air and fuel that will allow for proper combustion. During the intake stroke, the intake valve between the carburetor and combustion chamber opens. This allows atmospheric pressure to force the air-fuel mixture into the cylinder bore as the piston moves downward.\
				<h5>Step 2: Compression Stroke</h5>\
				Just after the piston moves to the bottom of its travel (bottom dead center), the cylinder bore contains the maximum air-fuel mixture possible. The intake valve closes and the piston returns back up the cylinder bore. This is called the compression stroke of the 4-cycle engine process. The air-fuel mixture is compressed between the piston and cylinder head.\
				<h5>Step 3: Power Stroke</h5>\
				When the piston reaches the top of its travel (top dead center), it will be at its optimum point to ignite the fuel to get maximize power to your outdoor power equipment. A very high voltage is created in the ignition coil. The spark plug enables this high voltage to be discharged into the combustion chamber. The heat created by the spark ignites the gases, creating rapidly expanding, super-heated gases that force the piston back down the cylinder bore. This is called the power stroke.\
				<h5>Step 4: Exhaust Stroke</h5>\
				When the piston reaches bottom dead center again, the exhaust valve opens. As the piston travels back up the cylinder bore, it forces the spent combustion gases through the exhaust valve and out of the exhaust systems. As the piston returns to top dead center, the exhaust valve closes and the intake valve opens and the 4-cycle engine process repeat.\
				Ever repetition of the cycle requires two full rotations of the crankshaft, while the engine only creates power during one of the four strokes. To keep the machine running, it needs the small engine flywheel. The power stroke creates momentum that pushes the flywheel’s inertia keeps it and the crankshaft turning during the exhaust, intake and compression strokes.',
            references: [
                'http://www.animatedengines.com/otto.html',
				'https://www.linkedin.com/pulse/20140717090644-133229807-principles-and-working-of-four-stroke-gasoline-engine',
				'https://www.briggsandstratton.com/na/en_us/support/videos/browse/4-cycle-theory.html'
            ],
            arrow_tail_path_d:'M244,339 C163,473 351,475 582,487',
            arrow_head_path_d:'M551,511 C636,481 588,522 576,460'
        },
        {
            elemCode: 'differential',
            elemName: 'Differential System',
            parentGrpName: 'RWD',
            youTubeUrl: 'https://www.youtube.com/embed/SOgoejxzF8c',
            sampleImageUrl: 'https://thumbs.gfycat.com/KaleidoscopicObedientDipper-max-1mb.gif',
            explanation: 'For the non-driven wheels on your car -- the front wheels on a rear-wheel drive car, \
            the back wheels on a front-wheel drive car -- this is not an issue. There is no connection between them, \
            so they spin independently. But the driven wheels are linked together so that a single engine and transmission can turn both wheels. \
            If your car did not have a differential, the wheels would have to be locked together, forced to spin at the same speed. \
            This would make turning difficult and hard on your car: For the car to be able to turn, one tire would have to slip. \
            With modern tires and concrete roads, a great deal of force is required to make a tire slip. \
            That force would have to be transmitted through the axle from one wheel to another, putting a heavy strain on the axle components.\
            <h5>Parts of a Differential</h5>\
            We will now learn how the differential achieves this in a step-by-step manner using the simplest configuration. \
            Power from the engine is transferred to the ring gear through a pinion gear. The ring gear is connected to a spider gear.\
            The spider gear lies at the heart of the differential, and special mention should be made about its rotation. The spider gear is free to make 2 kinds of rotations: one along with the ring gear (rotation) and the second on its own axis (spin).\
            The spider gear is meshed with 2 side gears. You can see that both the spider and side gears are bevel gears. Power flow from the drive shaft to the drive wheels follows the following pattern. \
            From the drive shaft power is transferred to the pinion gear first, and since the pinion and ring gear are meshed, power flows to the ring gear. \
            As the spider gear is connected with the ring gear, power flows to it. \
            Finally from the spider gear, power gets transferred to both the side gears.',
            references: [
                'https://www.youtube.com/watch?v=PEdnH7_7_yc',
				'http://www.learnengineering.org/2014/05/working-of-differential.html',
				'https://auto.howstuffworks.com/differential.htm'
            ],
            arrow_tail_path_d:'M504,229 C490,343 651,265 582,397',
            arrow_head_path_d:'M555,357 C593,420 532,415 608,380'
        }
		
    ];

    // public getContent(elemCode:string):Promise<Content>{
    //     return new Promise( (resolve, reject) => {
    //         let tempContent = this._allContent.find(cont => cont.elemCode==elemCode)

    //         if(tempContent) resolve(tempContent)
    //         else reject("Content for such element does not exist")
    //     });
    // }

    public getContent(elemCode:string):Content{
        return this._allContent.find(cont => cont.elemCode==elemCode)
    }
}